# Shameless copy of @AlastairUK's fine work for the jpl_eph repo.
# Extended a bit to include additional libraries.
name: Build

on: [push, pull_request]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make ERRORS=Y liblunar.a
        make install
        cd ..
        git clone https://github.com/Bill-Gray/sat_code
        cd sat_code
        make ERRORS=Y libsatell.a
        make install_lib
        cd ..
        git clone https://github.com/Bill-Gray/jpl_eph
        cd jpl_eph
        make ERRORS=Y libjpl.a
        make install
        cd ..
        make fo eph2tle cssfield roottest
        wget https://raw.githubusercontent.com/Bill-Gray/PDCursesMod/master/curses.h
        make VT=Y findorb.o

  buildOSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make ERRORS=Y CLANG=Y liblunar.a
        make install
        cd ..
        git clone https://github.com/Bill-Gray/sat_code
        cd sat_code
        make ERRORS=Y CLANG=Y libsatell.a
        make install_lib
        cd ..
        git clone https://github.com/Bill-Gray/jpl_eph
        cd jpl_eph
        make ERRORS=Y CLANG=Y libjpl.a
        make install
        cd ..
        make CLANG=Y fo eph2tle cssfield roottest
        wget https://raw.githubusercontent.com/Bill-Gray/PDCursesMod/master/curses.h
        make CLANG=Y VT=Y findorb.o

  buildWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        mkdir myincl

        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        nmake -f lunar.mak lunar64.lib
        copy lunar64.lib ..
        nmake -f lunar.mak install
        cd ..

        git clone https://github.com/Bill-Gray/sat_code
        cd sat_code
        nmake -f msvc.mak sat_code64.lib
        copy sat_code64.lib ..
        nmake -f msvc.mak install
        cd ..

        git clone https://github.com/Bill-Gray/jpl_eph
        cd jpl_eph
        set CL=/I"../myincl"
        nmake -f vc.mak jpleph64.lib
        copy jpleph64.lib ..
        copy jpleph.h ..\myincl
        cd ..

        set CL=/I"./myincl"
        nmake -f dos_find.mak fo.exe cssfield.exe eph2tle.exe roottest.exe

        cl -W4 -Ox win_get.c urlmon.lib
        win_get https://raw.githubusercontent.com/Bill-Gray/PDCursesMod/master/curses.h curses.h
        nmake -f dos_find.mak findorb.obj

      shell: cmd
